[package]
name = "scraping"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1", features = ["behavior-version-latest"] }
serde_dynamo = { version = "4", features = ["aws-sdk-dynamodb+1"] }
chromiumoxide = "0.9"
futures = "0.3"
axum = { version = "0.8" }
lambda_http = "1.0.0"
lambda_runtime = "1"
async-trait = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }

[[bin]]
name = "http_handler"
path = "src/http_handler.rs"

[[bin]]
name = "event_handler"
path = "src/event_handler.rs"

[[bin]]
name = "run_job"
path = "src/run_job.rs"
