service: scraping-service

provider:
  name: aws
  region: eu-west-1
  architecture: arm64
  ecr:
    images:
      api:
        path: .
        file: Dockerfile
      executor:
        path: .
        file: Dockerfile
        buildArgs:
          BIN_NAME: event_handler
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.jobsTableName}"
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource: "arn:aws:s3:::${self:custom.jobsBucketName}/*"

custom:
  jobsTableName: scraping-jobs
  jobsBucketName: scraping-jobs-actions

package:
  individually: true

functions:
  api:
    image:
      name: api
    memorySize: 1024
    timeout: 29
    environment:
      JOBS_TABLE_NAME: ${self:custom.jobsTableName}
      JOBS_BUCKET_NAME: ${self:custom.jobsBucketName}
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

  executor:
    image:
      name: executor
    memorySize: 2048
    timeout: 300
    environment:
      JOBS_TABLE_NAME: ${self:custom.jobsTableName}
      JOBS_BUCKET_NAME: ${self:custom.jobsBucketName}

resources:
  Resources:
    JobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.jobsTableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    JobsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.jobsBucketName}
